import React from 'react';
import { X, Sparkles, Loader2 } from 'lucide-react';
import { marked } from 'marked';

interface AiInsightModalProps {
  insight: string;
  isLoading: boolean;
  onClose: () => void;
}

const AiInsightModal: React.FC<AiInsightModalProps> = ({ insight, isLoading, onClose }) => {
  // Basic sanitization to prevent potential XSS from markdown if it were ever user-provided.
  const formattedInsight = isLoading ? '' : marked.parse(insight, { breaks: true, gfm: true });

  return (
    <div className="fixed inset-0 bg-black bg-opacity-60 flex items-center justify-center z-50 backdrop-blur-sm p-4 animate-fade-in-down">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl transform transition-all flex flex-col max-h-[90vh]">
        <header className="flex-shrink-0 flex items-center justify-between p-4 border-b border-gray-200">
          <div className="flex items-center gap-3">
            <Sparkles className="text-indigo-600" size={24}/>
            <h2 className="text-xl font-bold text-gray-800">AI-Powered Insights</h2>
          </div>
          <button onClick={onClose} className="p-2 rounded-full text-gray-500 hover:bg-gray-100">
            <X size={24} />
          </button>
        </header>
        <main className="p-6 overflow-y-auto">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center text-center text-gray-600 h-64">
              <Loader2 className="w-12 h-12 animate-spin text-indigo-500" />
              <p className="mt-4 text-lg font-semibold">Analyzing your data...</p>
              <p className="text-sm mt-1">This may take a moment.</p>
            </div>
          ) : (
            <div 
              className="prose prose-sm sm:prose-base max-w-none prose-headings:text-gray-800 prose-strong:text-gray-700"
              dangerouslySetInnerHTML={{ __html: formattedInsight }}
            />
          )}
        </main>
         <footer className="flex-shrink-0 p-3 bg-gray-50 rounded-b-2xl border-t text-center">
            <p className="text-xs text-gray-500">Insights are generated by AI and may not be perfect. Always verify with your own business knowledge.</p>
        </footer>
      </div>
    </div>
  );
};

export default AiInsightModal;
